import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getCurrentUser } from "@/server/auth/session";
import { requireEventCapability } from "@/server/permissions/capabilities";
import { getPrisma } from "@/lib/prisma";
import { createCompetition, syncCompetitionEntries } from "./actions";

export default async function CompetitionsPage({params}:{params:Promise<{eventId:string}>}){
  const user=await getCurrentUser();if(!user)redirect("/login");const {eventId}=await params;await requireEventCapability(user.id,eventId,"event.read");
  const event=await getPrisma().event.findUnique({where:{id:eventId},include:{teams:{where:{status:"ACTIVE"},orderBy:{name:"asc"}},activities:{orderBy:{title:"asc"}},competitions:{include:{_count:{select:{matches:true}}},orderBy:{createdAt:"desc"}},participationEntries:{where:{kind:"TEAM"}}}});if(!event)notFound();
  return <main><div className="page-heading"><div><h1>Competitions</h1><p className="muted">Reusable match engines. A tug-of-war, head-to-head quiz, relay playoff, or any future duel can use the same competition runtime.</p></div><form action={syncCompetitionEntries}><input type="hidden" name="eventId" value={event.id}/><button className="secondary">Sync team entries</button></form></div>
    <section className="card"><h2>Create competition</h2><form action={createCompetition} className="grid"><input type="hidden" name="eventId" value={event.id}/><label>Competition name<input name="name" required placeholder="e.g. Inter-team challenge"/></label><label>Format<select name="format" defaultValue="round_robin"><option value="round_robin">Round robin</option><option value="single_elimination">Single elimination</option></select></label><label>Optional linked activity<select name="activityInstanceId"><option value="">No linked activity</option>{event.activities.map((activity)=><option key={activity.id} value={activity.id}>{activity.title}</option>)}</select></label><label>Round-robin win points<input name="winPoints" type="number" step="any" defaultValue="3"/></label><label>Draw points<input name="drawPoints" type="number" step="any" defaultValue="1"/></label><label>Loss points<input name="lossPoints" type="number" step="any" defaultValue="0"/></label><label>Allow draws<select name="allowDraws" defaultValue="true"><option value="true">Yes</option><option value="false">No</option></select></label><fieldset className="full-span"><legend>Entrants — choose any active teams</legend><div className="entrant-grid">{event.teams.map((team)=><label className="check" key={team.id}><input type="checkbox" name="teamIds" value={team.id}/>{team.name}</label>)}</div></fieldset><div className="form-actions"><button>Create competition</button></div></form></section>
    {event.competitions.length===0?<section className="card"><p>No competitions yet.</p></section>:<div className="list-stack">{event.competitions.map((competition)=><article className="card" key={competition.id}><div className="section-heading"><div><div className="row"><h2>{competition.name}</h2><span className="badge">{competition.state}</span></div><p className="muted"><code>{competition.formatKey}</code> · {competition._count.matches} match{competition._count.matches===1?"":"es"}</p></div><Link className="button secondary" href={`/admin/events/${event.id}/competitions/${competition.id}`}>Open competition</Link></div></article>)}</div>}
  </main>;
}
