import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentUser } from "@/server/auth/session";
import { hasPlatformCapability } from "@/server/permissions/capabilities";
import { getPrisma } from "@/lib/prisma";
import { RetentionService } from "@/server/services/retention-service";
import { approvePia, completeBackup, createDataSubjectRequest, createIncident, createPia, publishPrivacyNotice, purgeEventRetention, startBackup, updateDataSubjectRequest, updateIncidentStatus } from "./actions";

export default async function SecurityPage() {
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  const [canSecurity, canPrivacy, canBackup] = await Promise.all([hasPlatformCapability(user.id, "security.manage"), hasPlatformCapability(user.id, "privacy.manage"), hasPlatformCapability(user.id, "backup.manage")]);
  if (!canSecurity && !canPrivacy && !canBackup) redirect("/admin");
  const organization = await getPrisma().organization.findFirstOrThrow();
  const [notices, pias, incidents, requests, backups, events] = await Promise.all([
    getPrisma().privacyNotice.findMany({ where: { organizationId: organization.id }, orderBy: { version: "desc" }, take: 8 }),
    getPrisma().privacyImpactAssessment.findMany({ where: { organizationId: organization.id }, orderBy: { createdAt: "desc" }, take: 10 }),
    getPrisma().securityIncident.findMany({ where: { organizationId: organization.id }, orderBy: { discoveredAt: "desc" }, take: 10 }),
    getPrisma().dataSubjectRequest.findMany({ where: { organizationId: organization.id }, orderBy: { receivedAt: "desc" }, take: 10 }),
    getPrisma().backupRun.findMany({ where: { organizationId: organization.id }, orderBy: { startedAt: "desc" }, take: 8 }),
    getPrisma().event.findMany({ where: { organizationId: organization.id }, orderBy: { startsAt: "desc" }, take: 30 }),
  ]);
  const retentionPreviews = await Promise.all(events.map((event) => new RetentionService().previewEvent(event.id, organization.id)));
  return <main>
    <div className="page-heading"><div><h1>Security & privacy</h1><p className="muted">Government-system hardening: privacy governance, incidents, retention, backups, data-subject requests, and operational evidence.</p></div><Link className="button secondary" href="/admin">Back to organizer</Link></div>

    <section className="card"><div className="section-heading"><div><h2>Security & privacy permissions</h2><p className="muted">Security: {canSecurity ? "enabled" : "read-only"} · Privacy: {canPrivacy ? "enabled" : "read-only"} · Backups: {canBackup ? "enabled" : "read-only"}</p></div></div></section>

    <section className="card"><div className="section-heading"><div><h2>Privacy notice</h2><p className="muted">Publish a versioned notice; events can reference a published notice without mutating historical copies.</p></div></div>
      <form action={publishPrivacyNotice} className="stack"><label>Title<input name="title" required defaultValue="MPW Team Building Platform Privacy Notice"/></label><label>Notice content<textarea name="content" required placeholder="Describe the data collected, purposes, lawful basis, recipients, retention, rights, and contact details."/></label><button disabled={!canPrivacy}>Publish new notice version</button></form>
      <div className="list-stack">{notices.map((n) => <div className="subcard" key={n.id}><strong>v{n.version} · {n.title}</strong><span className="muted">Published: {n.publishedAt?.toLocaleString() || "draft"} · checksum {n.checksum.slice(0, 12)}…</span></div>)}</div>
    </section>

    <section className="card"><h2>Privacy Impact Assessments</h2><p className="muted">A PIA record is evidence of the system-level privacy review. This is not a legal determination by the software.</p>
      <form action={createPia} className="grid"><label>System name<input name="systemName" required defaultValue="MPW Team Building Platform"/></label><label>Event ID (optional)<select name="eventId" defaultValue=""><option value="">Organization-wide</option>{events.map((e)=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Purpose<input name="purpose" required placeholder="Run government team-building activities and record results"/></label><label>Risk level<select name="riskLevel" defaultValue="MEDIUM"><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label>Scope / processing description<textarea name="scope" required/></label><label>Data inventory<textarea name="dataInventory" required placeholder="Names, team assignments, participation records, media, scores..."/></label><label>Risks<textarea name="risks" required/></label><label>Safeguards<textarea name="safeguards" required/></label><div><button disabled={!canPrivacy}>Create PIA record</button></div></form>
      <div className="list-stack">{pias.map((pia) => <details className="subcard" key={pia.id}><summary><strong>{pia.systemName}</strong> · {pia.status} · {pia.riskLevel}</summary><div className="details-body"><p className="muted">Purpose: {pia.purpose}</p>{pia.status !== "APPROVED" && <form action={approvePia} className="row"><input type="hidden" name="piaId" value={pia.id}/><label>Review due<input name="reviewDueAt" type="date"/></label><button disabled={!canPrivacy}>Approve PIA</button></form>}</div></details>)}</div>
    </section>

    <section className="card"><h2>Security incidents / breach register</h2><form action={createIncident} className="grid"><label>Event (optional)<select name="eventId" defaultValue=""><option value="">Platform-wide</option>{events.map((e)=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Severity<select name="severity" defaultValue="MEDIUM"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Category<input name="category" required placeholder="authentication / media / availability / privacy"/></label><label>Title<input name="title" required/></label><label>Affected subjects (optional)<input name="affectedSubjectsCount" type="number" min="0"/></label><label>Notification due (optional)<input name="notificationDueAt" type="datetime-local"/></label><label>Description<textarea name="description" required/></label><div><button disabled={!canSecurity}>Record incident</button></div></form>
      <div className="list-stack">{incidents.map((incident) => <details className="subcard" key={incident.id}><summary><strong>{incident.title}</strong> · {incident.severity} · {incident.status}</summary><div className="details-body"><p>{incident.description}</p><form action={updateIncidentStatus} className="grid"><input type="hidden" name="incidentId" value={incident.id}/><label>Status<select name="status" defaultValue={incident.status}><option>OPEN</option><option>CONTAINED</option><option>RESOLVED</option><option>CLOSED</option></select></label><label>Reason<input name="reason"/></label><button disabled={!canSecurity}>Update status</button></form></div></details>)}</div>
    </section>

    <section className="card"><h2>Data-subject requests</h2><form action={createDataSubjectRequest} className="grid"><label>Name<input name="subjectName" required/></label><label>Contact<input name="subjectContact"/></label><label>Request type<select name="requestType" defaultValue="ACCESS"><option>ACCESS</option><option>RECTIFICATION</option><option>ERASURE</option><option>RESTRICTION</option><option>OBJECTION</option><option>PORTABILITY</option><option>OTHER</option></select></label><label>Event (optional)<select name="eventId" defaultValue=""><option value="">Organization-wide</option>{events.map((e)=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Person ID (optional)<input name="personId"/></label><label>Details<textarea name="details"/></label><button disabled={!canPrivacy}>Register request</button></form>
      <div className="list-stack">{requests.map((request) => <details className="subcard" key={request.id}><summary><strong>{request.subjectName}</strong> · {request.requestType} · {request.status}</summary><div className="details-body"><form action={updateDataSubjectRequest} className="grid"><input type="hidden" name="requestId" value={request.id}/><label>Status<select name="status" defaultValue={request.status}><option>RECEIVED</option><option>VERIFYING</option><option>IN_REVIEW</option><option>FULFILLED</option><option>DENIED</option><option>CLOSED</option></select></label><label>Response<textarea name="response"/></label><label>Reason<input name="reason"/></label><button disabled={!canPrivacy}>Update request</button></form></div></details>)}</div>
    </section>

    <section className="card"><h2>Backups & restore evidence</h2><p className="muted">The app records backup evidence; the actual PostgreSQL/object-storage backup remains an infrastructure responsibility. See the Phase 9 runbook.</p><form action={startBackup} className="grid"><label>Backup type<input name="backupType" required defaultValue="POSTGRESQL"/></label><label>Notes<input name="notes"/></label><button disabled={!canBackup}>Start backup record</button></form>
      <div className="list-stack">{backups.map((backup) => <details className="subcard" key={backup.id}><summary><strong>{backup.backupType}</strong> · {backup.status} · {backup.startedAt.toLocaleString()}</summary><div className="details-body"><form action={completeBackup} className="grid"><input type="hidden" name="backupId" value={backup.id}/><label>Status<select name="status" defaultValue={backup.status === "STARTED" ? "SUCCESS" : backup.status}><option>SUCCESS</option><option>FAILED</option><option>VERIFIED</option></select></label><label>External backup reference<input name="backupReference" defaultValue={backup.backupReference ?? ""}/></label><label>Checksum<input name="checksum" defaultValue={backup.checksum ?? ""}/></label><label>Notes<input name="notes" defaultValue={backup.notes ?? ""}/></label><button disabled={!canBackup}>Record backup result</button></form></div></details>)}</div>
    </section>

    <section className="card"><h2>Retention controls</h2><p className="muted">Only non-live events may be purged. Audit logs, roster/person records, snapshots, and final results are intentionally retained until a separate approved records schedule exists.</p><div className="list-stack">{retentionPreviews.map((preview, i) => { const event=events[i]; return <div className="subcard" key={event.id}><div className="row"><strong>{event.name}</strong><span className="badge">{event.state}</span><span className="muted">{preview.configured ? `cutoff ${preview.cutoff?.toLocaleString()}` : "no retention period configured"}</span></div><p className="muted">Sessions {preview.counts.participantSessions} · Media {preview.counts.mediaAssets} · Receipts {preview.counts.operationalReceipts} · Domain events {preview.counts.domainEvents} · Exports {preview.counts.exportJobs}</p>{preview.configured && ["FINALIZED","ARCHIVED","CANCELLED"].includes(event.state) && <form action={purgeEventRetention}><input type="hidden" name="eventId" value={event.id}/><button className="secondary" disabled={!canPrivacy}>Purge expired operational data</button></form>}</div>})}</div></section>

    <section className="card"><h2>Operational policy</h2><ul><li>Do not store passwords, raw team codes, session tokens, or secret keys in logs.</li><li>Use the event retention setting only after the agency has approved the underlying records schedule.</li><li>Security incidents must be assessed promptly; where mandatory notification applies, NPC guidance currently points to the 72-hour notification process.</li><li>PIAs and privacy notices are versioned evidence, not substitutes for the agency DPO's legal/privacy review.</li></ul></section>
  </main>;
}
