import { randomUUID } from "node:crypto";
import { notFound, redirect } from "next/navigation";
import { getCurrentUser } from "@/server/auth/session";
import { requireEventCapability } from "@/server/permissions/capabilities";
import { getPrisma } from "@/lib/prisma";
import { ActivityDefinitionSchema } from "@/schemas/activity";
import { LeaderboardDefinitionSchema } from "@/schemas/results";
import { LeaderboardService } from "@/server/services/leaderboard-service";
import { LiveRefresh } from "@/features/live-ops/LiveRefresh";
import { PlacementRuleBuilder } from "@/features/scoring/PlacementRuleBuilder";
import { addLeaderboardSource, addScoreAdjustment, addTieBreaker, applyPlacementPoints, createLeaderboard, reverseScoreEntry, snapshotLeaderboard, syncTeamEntries } from "./actions";

export default async function ScoresPage({params}:{params:Promise<{eventId:string}>}){
  const user=await getCurrentUser();if(!user)redirect("/login");const {eventId}=await params;await requireEventCapability(user.id,eventId,"event.read");
  const event=await getPrisma().event.findUnique({where:{id:eventId},include:{teams:{where:{status:"ACTIVE"},orderBy:{name:"asc"}},activities:{include:{versions:{orderBy:{version:"desc"}}},orderBy:{title:"asc"}},leaderboards:{include:{snapshots:{orderBy:{revision:"desc"},take:5}},orderBy:{createdAt:"asc"}},participationEntries:{include:{team:true}},}});if(!event)notFound();
  const ledger=await getPrisma().scoreEntry.findMany({where:{eventId},include:{participationEntry:{include:{team:true}},activityInstance:true},orderBy:{createdAt:"desc"},take:80});
  const leaderboardService=new LeaderboardService();
  const boards=await Promise.all(event.leaderboards.map(async(board)=>({board,config:LeaderboardDefinitionSchema.parse(board.configJson),standings:await leaderboardService.live(board.id)})));
  const activityHints=event.activities.map((activity)=>{const current=activity.versions.find((v)=>v.id===activity.currentVersionId)||activity.versions[0];let scoringKey="";let metrics:string[]=[];if(current){try{const d=ActivityDefinitionSchema.parse(current.definitionJson);scoringKey=d.scoring?.outputKey||"";metrics=d.metrics.map((m)=>m.key);}catch{}}return{id:activity.id,title:activity.title,scoringKey,metrics};});
  return <main><div className="page-heading"><div><h1>Scores & leaderboards</h1><p className="muted">Review standings, apply bonuses or penalties, and finalize results from one place.</p></div><LiveRefresh seconds={10}/></div>
    <section className="card"><div className="section-heading"><div><h2>Team score identities</h2><p className="muted">Every team competes through a reusable participation entry. New teams get one automatically; sync covers older/imported teams.</p></div><form action={syncTeamEntries}><input type="hidden" name="eventId" value={event.id}/><button className="secondary">Sync active teams</button></form></div><div className="stats-grid"><div className="stat"><strong>{event.teams.length}</strong><span>active teams</span></div><div className="stat"><strong>{event.participationEntries.filter((e)=>e.kind==="TEAM").length}</strong><span>team entries</span></div><div className="stat"><strong>{ledger.length}</strong><span>recent ledger rows loaded</span></div></div></section>

    <section className="card"><div className="section-heading"><div><h2>Create a leaderboard</h2><p className="muted">For most events, give it a name and use the standard points setup. Advanced scoring rules are still available when needed.</p></div></div><form action={createLeaderboard} className="stack"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="sourceId" value="main"/><input type="hidden" name="sourceLabel" value="Activity points"/><input type="hidden" name="dimensionKey" value="activity_points"/><input type="hidden" name="scope" value="ACTIVITY"/><input type="hidden" name="weight" value="1"/><input type="hidden" name="valueDirection" value="DESC"/><input type="hidden" name="attemptMode" value="BEST"/><input type="hidden" name="selectionMode" value="ALL"/><input type="hidden" name="selectionCount" value="1"/><input type="hidden" name="primaryDirection" value="DESC"/><input type="hidden" name="rankStyle" value="COMPETITION"/><div className="grid"><label>Leaderboard name<input name="name" required placeholder="e.g. Overall standings"/></label></div><details className="secondary-details"><summary>Limit this leaderboard to selected activities</summary><fieldset className="details-body"><legend>Leave everything unchecked to include all activities</legend><div className="entrant-grid">{event.activities.map((activity)=><label className="check" key={activity.id}><input type="checkbox" name="activityIds" value={activity.id}/>{activity.title}</label>)}</div></fieldset></details><div className="form-actions"><button>Create leaderboard</button></div></form></section>

    {boards.map((boardResult)=>{ const {board,config,standings}=boardResult; return <section className="card" key={board.id}><div className="section-heading"><div><div className="row"><h2>{board.name}</h2><span className="badge">LIVE</span></div><p className="muted">{config.sources.length} scoring source{config.sources.length===1?"":"s"}{config.tieBreakers.length ? ` · ${config.tieBreakers.length} tie-break rule${config.tieBreakers.length===1?"":"s"}` : ""}</p></div><div className="row"><form action={snapshotLeaderboard}><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="leaderboardId" value={board.id}/><input type="hidden" name="state" value="PROVISIONAL"/><button className="secondary">Save provisional</button></form><form action={snapshotLeaderboard}><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="leaderboardId" value={board.id}/><input type="hidden" name="state" value="FINAL"/><button>Finalize snapshot</button></form></div></div>
      <div className="table-wrap"><table><thead><tr><th>Rank</th><th>Entry</th>{config.sources.map((s)=><th key={s.id}>{s.label}</th>)}<th>Total</th><th>Penalties</th></tr></thead><tbody>{standings.map((row)=><tr key={row.entryId}><td><strong>#{row.rank}</strong></td><td>{row.label}</td>{config.sources.map((s)=><td key={s.id}>{(row.componentTotals[s.id]??0).toFixed(2)}</td>)}<td><strong>{row.total.toFixed(2)}</strong></td><td>{row.penaltyTotal.toFixed(2)}</td></tr>)}</tbody></table></div>
      <details><summary>Add aggregation source</summary><form action={addLeaderboardSource} className="grid details-body"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="leaderboardId" value={board.id}/><label>Source ID<input name="sourceId" pattern="[a-z0-9_-]+" required/></label><label>Label<input name="sourceLabel" required/></label><label>Dimension key<input name="dimensionKey" required/></label><label>Scope<select name="scope"><option value="ACTIVITY">Activity</option><option value="EVENT">Event adjustments</option></select></label><label>Weight<input name="weight" type="number" step="any" defaultValue="1"/></label><label>Within-source better value<select name="valueDirection" defaultValue="DESC"><option value="DESC">Higher</option><option value="ASC">Lower</option></select></label><label>Attempts<select name="attemptMode" defaultValue="BEST"><option>BEST</option><option>LATEST</option><option>SUM</option><option>AVERAGE</option></select></label><label>Selection<select name="selectionMode"><option value="ALL">All</option><option value="BEST_N">Best N</option><option value="DROP_LOWEST_N">Drop lowest N</option></select></label><label>N<input name="selectionCount" type="number" min="0" defaultValue="1"/></label><fieldset className="full-span"><legend>Optional activity filter</legend><div className="entrant-grid">{event.activities.map((activity)=><label className="check" key={activity.id}><input type="checkbox" name="activityIds" value={activity.id}/>{activity.title}</label>)}</div></fieldset><div className="form-actions"><button className="secondary">Add source</button></div></form></details>
      <details><summary>Add tie-breaker</summary><form action={addTieBreaker} className="grid details-body"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="leaderboardId" value={board.id}/><label>Type<select name="type"><option value="SOURCE_TOTAL">Source total</option><option value="SCORE_DIMENSION">Any score dimension</option><option value="FEWER_PENALTIES">Fewer penalties</option><option value="EARLIER_COMPLETION">Earlier completion</option><option value="DECLARE_TIE">Declare tie</option></select></label><label>Source ID<input name="sourceId" placeholder="for source-total"/></label><label>Dimension key<input name="dimensionKey" placeholder="for score-dimension"/></label><label>Direction<select name="direction"><option value="DESC">Higher first</option><option value="ASC">Lower first</option></select></label><div className="form-actions"><button className="secondary">Append tie-breaker</button></div></form></details>
      {board.snapshots.length>0&&<details><summary>Result revisions</summary><div className="table-wrap details-body"><table><thead><tr><th>Revision</th><th>State</th><th>Created</th><th>Input hash</th></tr></thead><tbody>{board.snapshots.map((snap)=><tr key={snap.id}><td>r{snap.revision}</td><td>{snap.state}</td><td>{snap.createdAt.toLocaleString("en-PH",{timeZone:event.timezone})}</td><td><code>{snap.inputHash.slice(0,12)}</code></td></tr>)}</tbody></table></div></details>}
    </section>;})}

    <section className="card"><h2>Convert placements to points</h2><p className="muted">Rank any activity by a raw metric or score dimension, then map arbitrary rank bands to a new ledger dimension. Recomputes reverse the previous placement generation instead of overwriting it.</p><form action={applyPlacementPoints} className="grid"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="idempotencyKey" value={randomUUID()}/><label>Activity<select name="activityInstanceId" required>{activityHints.map((a)=><option key={a.id} value={a.id}>{a.title}{a.scoringKey?` · score: ${a.scoringKey}`:""}</option>)}</select></label><label>Source type<select name="sourceType"><option value="SCORE">Derived score</option><option value="METRIC">Raw metric</option></select></label><label>Source key<input name="sourceKey" required placeholder="activity_points / elapsed_ms / volume_ml"/></label><label>Better result<select name="direction"><option value="DESC">Higher</option><option value="ASC">Lower</option></select></label><label>Attempts<select name="attemptMode" defaultValue="BEST"><option>BEST</option><option>LATEST</option><option>SUM</option><option>AVERAGE</option></select></label><label>Tie tolerance<input name="tieTolerance" type="number" min="0" step="any" defaultValue="0"/></label><label>Output dimension<input name="outputDimensionKey" pattern="[a-z0-9_-]+" defaultValue="event_points" required/></label><PlacementRuleBuilder/><div className="form-actions"><button>Apply placement points</button></div></form></section>

    <section className="card"><h2>Manual bonus / penalty / override</h2><form action={addScoreAdjustment} className="grid"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="idempotencyKey" value={randomUUID()}/><label>Team<select name="teamId" required>{event.teams.map((team)=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label>Dimension<input name="dimensionKey" pattern="[a-z0-9_-]+" defaultValue="event_points" required/></label><label>Type<select name="entryType"><option>BONUS</option><option>PENALTY</option><option>MANUAL</option><option>OVERRIDE_DELTA</option></select></label><label>Amount<input name="amount" type="number" step="any" required/></label><label>Optional activity<select name="activityInstanceId"><option value="">Event-level</option>{event.activities.map((a)=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><label className="full-span">Reason<input name="reason" required placeholder="Required for audit trail"/></label><div className="form-actions"><button>Add ledger entry</button></div></form></section>

    <section className="card"><h2>Score audit ledger</h2><div className="table-wrap"><table><thead><tr><th>Time</th><th>Entry</th><th>Scope</th><th>Dimension</th><th>Type</th><th>Amount</th><th>Reason</th><th></th></tr></thead><tbody>{ledger.map((row)=><tr key={row.id}><td>{row.createdAt.toLocaleTimeString("en-PH",{timeZone:event.timezone})}</td><td>{row.participationEntry.team?.name||row.participationEntry.label||row.participationEntryId.slice(0,8)}</td><td>{row.activityInstance?.title||"Event"}</td><td><code>{row.dimensionKey}</code></td><td>{row.entryType}</td><td>{Number(row.amount.toString()).toFixed(2)}</td><td>{row.reason||"—"}</td><td>{row.entryType!=="REVERSAL"&&<form action={reverseScoreEntry} className="inline-form"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="scoreEntryId" value={row.id}/><input type="hidden" name="reason" value="Organizer reversal from score ledger"/><button className="text-button danger-text">Reverse</button></form>}</td></tr>)}</tbody></table></div></section>
  </main>;
}
