import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getCurrentUser } from "@/server/auth/session";
import { requireEventCapability } from "@/server/permissions/capabilities";
import { getPrisma } from "@/lib/prisma";
import { EventConfigSchema } from "@/schemas/event";
import { TechnicalLimits } from "@/schemas/shared";
import { addParticipant, archiveTeam, assignParticipantTeam, bulkCreateTeams, createTeam, updateTeam } from "./actions";

export default async function EventPeoplePage({ params }: { params: Promise<{ eventId: string }> }) {
  const user=await getCurrentUser(); if(!user) redirect("/login"); const {eventId}=await params; await requireEventCapability(user.id,eventId,"event.read");
  const event=await getPrisma().event.findUnique({where:{id:eventId},include:{teams:{orderBy:{createdAt:"asc"}},participants:{include:{person:true,teamMemberships:{where:{status:"ACTIVE"},include:{team:true}}},orderBy:{createdAt:"asc"}}}}); if(!event) notFound();
  const config=EventConfigSchema.parse(event.configJson); const activeTeams=event.teams.filter((team)=>team.status==="ACTIVE");
  return <main>
    <div className="page-heading"><div><div className="eyebrow">Step 2</div><h1>Teams & people</h1><p className="muted">Add only what you need. You can come back anytime.</p></div><Link className="button secondary" href={`/admin/events/${event.id}/library`}>Next: Pick activities →</Link></div>
    <div className="people-summary"><div className="stat"><strong>{activeTeams.length}</strong><span>active {config.terminology.team.toLowerCase()}s</span></div><div className="stat"><strong>{event.participants.length}</strong><span>{config.terminology.participant.toLowerCase()}s</span></div></div>

    <section className="card"><div className="section-heading"><div><h2>{config.terminology.team}s</h2><p className="muted">Create one at a time or generate numbered teams in bulk.</p></div></div>
      <div className="setup-choice-grid">
        <details className="subcard"><summary>Add one {config.terminology.team.toLowerCase()}</summary><form action={createTeam} className="grid details-body"><input type="hidden" name="eventId" value={event.id}/><label>Team name<input name="name" required placeholder="e.g. Team Blue"/></label><details className="full-span nested-details"><summary>Optional details</summary><div className="grid details-body"><label>Short label<input name="abbreviation" placeholder="e.g. BLUE"/></label><label>Join code<input name="teamCode" minLength={4} placeholder="Leave blank to add later"/></label></div></details><div className="form-actions"><button>Add {config.terminology.team.toLowerCase()}</button></div></form></details>
        <details className="subcard"><summary>Create several numbered teams</summary><form action={bulkCreateTeams} className="grid details-body"><input type="hidden" name="eventId" value={event.id}/><label>How many?<input name="count" type="number" min="1" max={TechnicalLimits.maxTeamsPerBulkOperation} required/></label><label>Name prefix<input name="namePrefix" defaultValue={config.terminology.team}/></label><details className="full-span nested-details"><summary>Numbering options</summary><div className="grid details-body"><label>Start at<input name="startNumber" type="number" min="0" defaultValue="1"/></label><input type="hidden" name="keyPrefix" value="team"/></div></details><div className="form-actions"><button>Create teams</button></div></form></details>
      </div>
      {event.teams.length===0?<div className="empty-state compact-empty"><strong>No teams yet</strong><span>Add teams when you are ready. You do not need them just to continue setting up the event.</span></div>:<div className="list-stack">{event.teams.map((team)=><details className="subcard" key={team.id}><summary><strong>{team.name}</strong><span className="muted">{team.status}</span></summary><form action={updateTeam} className="grid details-body"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="teamId" value={team.id}/><label>Name<input name="name" defaultValue={team.name} required/></label><label>Abbreviation<input name="abbreviation" defaultValue={team.abbreviation??""}/></label><label>Color token<input name="colorToken" defaultValue={team.colorToken??""}/></label><label>Logo asset ID<input name="logoAssetId" defaultValue={team.logoAssetId??""}/></label><label>Replace join code<input name="teamCode" minLength={4} placeholder="Leave blank to keep current"/></label><div className="form-actions"><button>Save team</button></div></form>{team.status==="ACTIVE"&&<form action={archiveTeam} className="details-body"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="teamId" value={team.id}/><button className="secondary">Archive team</button></form>}</details>)}</div>}
    </section>

    <section className="card"><div className="section-heading"><div><h2>{config.terminology.participant}s</h2><p className="muted">People can be added now or later, with or without app accounts.</p></div></div>
      <details className="subcard"><summary>Add a {config.terminology.participant.toLowerCase()}</summary><form action={addParticipant} className="grid details-body"><input type="hidden" name="eventId" value={event.id}/><label>Display name<input name="displayName" required/></label><label>Initial team<select name="teamId" defaultValue=""><option value="">Unassigned</option>{activeTeams.map((team)=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label><details className="full-span nested-details"><summary>Optional participant details</summary><div className="grid details-body"><label>External key<input name="externalKey" placeholder="Employee ID / source ID"/></label><label>Role<input name="roleKey" placeholder="captain / member / scorer ..."/></label></div></details><div className="form-actions"><button>Add participant</button></div></form></details>
      {event.participants.length===0?<div className="empty-state compact-empty"><strong>No participants yet</strong><span>You can add the roster later or let your event flow determine how people join.</span></div>:<div className="table-wrap"><table><thead><tr><th>Participant</th><th>Current team</th><th>Assign</th></tr></thead><tbody>{event.participants.map((participant)=>{const membership=participant.teamMemberships[0];return <tr key={participant.id}><td><strong>{participant.displayName||participant.person.displayName}</strong>{participant.person.externalKey&&<><br/><code>{participant.person.externalKey}</code></>}</td><td>{membership?.team.name||"Unassigned"}</td><td><form action={assignParticipantTeam} className="row compact-form"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="eventParticipantId" value={participant.id}/><select name="teamId" defaultValue={membership?.teamId??""}><option value="">Unassigned</option>{activeTeams.map((team)=><option key={team.id} value={team.id}>{team.name}</option>)}</select><input name="roleKey" defaultValue={membership?.roleKey??""} placeholder="role"/><button className="secondary">Update</button></form></td></tr>})}</tbody></table></div>}
    </section>
  </main>;
}
