"use client";

import { useState } from "react";
import type { ActivityBlock, QuestionBlock } from "@/schemas/activity";
import { BLOCK_CATALOG, builderId, createBlock, defaultNormalization } from "./model";

const inputLabel=(value:{default:string}|undefined)=>value?.default ?? "";
const withLabel=(value:string)=>({default:value});
const n=(value:string,fallback=0)=>{const x=Number(value);return Number.isFinite(x)?x:fallback;};

const QUESTION_TYPES: QuestionBlock["type"][] = ["single_select","multi_select","fill_blank","text_input","textarea","number_input","ordering","matching"];
function isQuestion(block: ActivityBlock): block is QuestionBlock { return QUESTION_TYPES.includes(block.type as QuestionBlock["type"]); }

export function BlockEditor({ block, index, total, onChange, onRemove, onMove, allowedTypes }: { block:ActivityBlock; index:number; total:number; onChange:(block:ActivityBlock)=>void; onRemove:()=>void; onMove:(direction:-1|1)=>void; allowedTypes?:ActivityBlock["type"][] }) {
  const catalog=BLOCK_CATALOG.find((item)=>item.type===block.type);
  const catalogItems=allowedTypes?BLOCK_CATALOG.filter((item)=>allowedTypes.includes(item.type)):BLOCK_CATALOG;
  const patchBase=(patch:Partial<ActivityBlock>)=>onChange({...block,...patch} as ActivityBlock);
  return <article className="builder-block">
    <div className="builder-block-head">
      <div><span className="badge">{catalog?.group}</span><strong>{catalog?.label ?? block.type}</strong><small className="muted"> #{index+1}</small></div>
      <div className="row"><button type="button" className="icon-button" disabled={index===0} onClick={()=>onMove(-1)} aria-label="Move block up">↑</button><button type="button" className="icon-button" disabled={index===total-1} onClick={()=>onMove(1)} aria-label="Move block down">↓</button><button type="button" className="text-button danger-text" onClick={onRemove}>Remove</button></div>
    </div>
    <div className="grid builder-base"><label>Block type<select value={block.type} onChange={(e)=>onChange(createBlock(e.target.value as ActivityBlock["type"]))}>{catalogItems.map((item)=><option key={item.type} value={item.type}>{item.group} — {item.label}</option>)}</select></label><label>Optional block title<input value={inputLabel(block.title)} onChange={(e)=>patchBase({title:e.target.value?withLabel(e.target.value):undefined})}/></label><label>Visibility<select value={block.visibleTo ?? "EVENT"} onChange={(e)=>patchBase({visibleTo:e.target.value as NonNullable<ActivityBlock["visibleTo"]>})}><option value="PUBLIC">Public</option><option value="EVENT">Event participants</option><option value="STAFF">Staff only</option><option value="PRIVATE">Private</option></select></label><label className="check"><input type="checkbox" checked={Boolean(block.required)} onChange={(e)=>patchBase({required:e.target.checked})}/>Required</label></div>
    <BlockFields block={block} onChange={onChange}/>
    {isQuestion(block)&&<QuestionMeta block={block} onChange={onChange}/>}
    <details className="advanced"><summary>Advanced block identity</summary><div className="details-body"><label>Stable block ID<input value={block.id} onChange={(e)=>patchBase({id:e.target.value})}/></label><p className="muted">Used by submissions and history. Keep stable after this activity is live.</p></div></details>
  </article>;
}

function PromptMedia({ value, onChange }:{value?:string;onChange:(value?:string)=>void}) { return <label>Optional prompt media asset ID<input value={value ?? ""} onChange={(e)=>onChange(e.target.value||undefined)} placeholder="asset reference"/></label>; }

function BlockFields({block,onChange}:{block:ActivityBlock;onChange:(block:ActivityBlock)=>void}) {
  switch(block.type){
    case "rich_text": return <label>Instructions / text<textarea className="builder-textarea" value={block.body.default} onChange={(e)=>onChange({...block,body:withLabel(e.target.value)})}/></label>;
    case "media_display": return <div className="grid"><label>Media asset ID<input value={block.mediaAssetId} onChange={(e)=>onChange({...block,mediaAssetId:e.target.value})}/></label><label>Media kind<select value={block.mediaKind} onChange={(e)=>onChange({...block,mediaKind:e.target.value as typeof block.mediaKind})}><option>IMAGE</option><option>AUDIO</option><option>VIDEO</option><option>FILE</option></select></label><label className="full-span">Caption<input value={inputLabel(block.caption)} onChange={(e)=>onChange({...block,caption:e.target.value?withLabel(e.target.value):undefined})}/></label></div>;
    case "single_select": return <div className="stack"><div className="grid"><label>Question<textarea className="builder-prompt" value={block.prompt.default} onChange={(e)=>onChange({...block,prompt:withLabel(e.target.value)})}/></label><PromptMedia value={block.promptMediaAssetId} onChange={(promptMediaAssetId)=>onChange({...block,promptMediaAssetId})}/></div><div className="row"><strong>Choices</strong><label className="check"><input type="checkbox" checked={Boolean(block.shuffleChoices)} onChange={(e)=>onChange({...block,shuffleChoices:e.target.checked})}/>Shuffle</label></div><div className="stack">{block.choices.map((choice,index)=><div className="choice-row" key={choice.id}><input type="radio" name={`correct-${block.id}`} checked={(block.validation.correctChoiceIds??[]).includes(choice.id)} onChange={()=>onChange({...block,validation:{correctChoiceIds:[choice.id]}})}/><input value={inputLabel(choice.label)} onChange={(e)=>onChange({...block,choices:block.choices.map((c,i)=>i===index?{...c,label:withLabel(e.target.value)}:c)})} placeholder={`Choice ${index+1}`}/><button type="button" className="text-button" disabled={block.choices.length<=2} onClick={()=>onChange({...block,choices:block.choices.filter((_,i)=>i!==index),validation:{correctChoiceIds:(block.validation.correctChoiceIds??[]).filter((id)=>id!==choice.id)}})}>Remove</button></div>)}</div><button type="button" className="secondary" onClick={()=>onChange({...block,choices:[...block.choices,{id:builderId("choice"),label:withLabel(`Choice ${block.choices.length+1}`)}]})}>+ Choice</button></div>;
    case "multi_select": return <div className="stack"><div className="grid"><label>Question<textarea className="builder-prompt" value={block.prompt.default} onChange={(e)=>onChange({...block,prompt:withLabel(e.target.value)})}/></label><PromptMedia value={block.promptMediaAssetId} onChange={(promptMediaAssetId)=>onChange({...block,promptMediaAssetId})}/></div><div className="row"><strong>Choices</strong><label className="check"><input type="checkbox" checked={Boolean(block.shuffleChoices)} onChange={(e)=>onChange({...block,shuffleChoices:e.target.checked})}/>Shuffle</label></div>{block.choices.map((choice,index)=><div className="choice-row" key={choice.id}><input type="checkbox" checked={(block.validation.correctChoiceIds??[]).includes(choice.id)} onChange={(e)=>{const current=block.validation.correctChoiceIds??[];onChange({...block,validation:{...block.validation,correctChoiceIds:e.target.checked?[...current,choice.id]:current.filter((id)=>id!==choice.id)}})}}/><input value={inputLabel(choice.label)} onChange={(e)=>onChange({...block,choices:block.choices.map((c,i)=>i===index?{...c,label:withLabel(e.target.value)}:c)})}/><button type="button" className="text-button" disabled={block.choices.length<=2} onClick={()=>onChange({...block,choices:block.choices.filter((_,i)=>i!==index),validation:{...block.validation,correctChoiceIds:(block.validation.correctChoiceIds??[]).filter((id)=>id!==choice.id)}})}>Remove</button></div>)}<button type="button" className="secondary" onClick={()=>onChange({...block,choices:[...block.choices,{id:builderId("choice"),label:withLabel(`Choice ${block.choices.length+1}`)}]})}>+ Choice</button><div className="grid"><label>Checking mode<select value={block.validation.correctnessMode} onChange={(e)=>onChange({...block,validation:{...block.validation,correctnessMode:e.target.value as typeof block.validation.correctnessMode}})}><option value="EXACT_SET">Exact set required</option><option value="PARTIAL_ALLOWED">Partial allowed</option></select></label><label>Minimum selections<input type="number" min="0" value={block.selection.min ?? ""} onChange={(e)=>onChange({...block,selection:{...block.selection,min:e.target.value?Math.max(0,n(e.target.value)):undefined}})}/></label><label>Maximum selections<input type="number" min="1" value={block.selection.max ?? ""} onChange={(e)=>onChange({...block,selection:{...block.selection,max:e.target.value?Math.max(1,n(e.target.value)):undefined}})}/></label></div></div>;
    case "fill_blank":
    case "text_input":
    case "textarea": return <TextQuestionFields block={block} onChange={onChange}/>;
    case "number_input": return <NumberQuestionFields block={block} onChange={onChange}/>;
    case "ordering": return <OrderingFields block={block} onChange={onChange}/>;
    case "matching": return <MatchingFields block={block} onChange={onChange}/>;
    case "question_pool": return <QuestionPoolFields block={block} onChange={onChange}/>;
    case "media_submission": return <div className="stack"><label>Prompt<textarea className="builder-prompt" value={block.prompt.default} onChange={(e)=>onChange({...block,prompt:withLabel(e.target.value)})}/></label><fieldset><legend>Accepted evidence</legend><div className="check-grid">{(["IMAGE","VIDEO","AUDIO","FILE"] as const).map((kind)=><label className="check" key={kind}><input type="checkbox" checked={block.acceptedKinds.includes(kind)} onChange={(e)=>{const next=e.target.checked?[...block.acceptedKinds,kind]:block.acceptedKinds.filter((x)=>x!==kind); if(next.length) onChange({...block,acceptedKinds:next})}}/>{kind}</label>)}</div></fieldset><div className="grid"><label>Minimum files<input type="number" min="0" value={block.minItems} onChange={(e)=>onChange({...block,minItems:Math.max(0,n(e.target.value))})}/></label><label>Maximum files<input type="number" min="1" value={block.maxItems} onChange={(e)=>onChange({...block,maxItems:Math.max(1,n(e.target.value,1))})}/></label><label className="check"><input type="checkbox" checked={block.requireMarshalReview} onChange={(e)=>onChange({...block,requireMarshalReview:e.target.checked})}/>Require marshal review</label></div></div>;
    case "manual_metric": return <div className="grid"><label>Prompt<textarea className="builder-prompt" value={block.prompt.default} onChange={(e)=>onChange({...block,prompt:withLabel(e.target.value)})}/></label><label>Metric key<input value={block.metricKey} pattern="[a-z0-9_-]+" onChange={(e)=>onChange({...block,metricKey:e.target.value})}/></label><label>Unit<input value={block.unit??""} onChange={(e)=>onChange({...block,unit:e.target.value||undefined})}/></label></div>;
    case "marshal_decision": return <div className="stack"><label>Prompt<textarea className="builder-prompt" value={block.prompt.default} onChange={(e)=>onChange({...block,prompt:withLabel(e.target.value)})}/></label><strong>Decision options</strong>{block.options.map((option,index)=><div className="choice-row" key={option.id}><input value={option.label.default} onChange={(e)=>onChange({...block,options:block.options.map((o,i)=>i===index?{...o,label:withLabel(e.target.value)}:o)})}/><button type="button" className="text-button" disabled={block.options.length<=2} onClick={()=>onChange({...block,options:block.options.filter((_,i)=>i!==index)})}>Remove</button></div>)}<button type="button" className="secondary" onClick={()=>onChange({...block,options:[...block.options,{id:builderId("option"),label:withLabel(`Option ${block.options.length+1}`)}]})}>+ Option</button></div>;
    case "judge_rubric": return <RubricFields block={block} onChange={onChange}/>;
    case "acknowledge": return <label>Statement<textarea className="builder-prompt" value={block.prompt.default} onChange={(e)=>onChange({...block,prompt:withLabel(e.target.value)})}/></label>;
  }
}

type TextBlock=Extract<ActivityBlock,{type:"fill_blank"|"text_input"|"textarea"}>;
function TextQuestionFields({block,onChange}:{block:TextBlock;onChange:(block:ActivityBlock)=>void}){
  const matcher=block.matcher;
  const setMatcherType=(type:"EXACT"|"CONTAINS"|"FUZZY"|"MANUAL_REVIEW")=>onChange({...block,matcher:type==="MANUAL_REVIEW"?{type}:{type,accepted:["Answer"],...(type==="FUZZY"?{threshold:0.9}:{}),normalization:defaultNormalization()}} as TextBlock);
  return <div className="stack"><div className="grid"><label>Prompt<textarea className="builder-prompt" value={block.prompt.default} onChange={(e)=>onChange({...block,prompt:withLabel(e.target.value)})}/></label><PromptMedia value={block.promptMediaAssetId} onChange={(promptMediaAssetId)=>onChange({...block,promptMediaAssetId})}/></div><div className="grid"><label>Answer checking<select value={matcher?.type ?? "MANUAL_REVIEW"} onChange={(e)=>setMatcherType(e.target.value as "EXACT"|"CONTAINS"|"FUZZY"|"MANUAL_REVIEW")}><option value="EXACT">Exact / accepted answers</option><option value="CONTAINS">Contains accepted phrase</option><option value="FUZZY">Fuzzy similarity</option><option value="MANUAL_REVIEW">Manual review</option></select></label><label>Maximum characters<input type="number" min="1" value={block.maxLength??""} onChange={(e)=>onChange({...block,maxLength:e.target.value?Math.max(1,n(e.target.value)):undefined})}/></label></div>{matcher&&matcher.type!=="MANUAL_REVIEW"&&<><strong>Accepted answers</strong>{matcher.accepted.map((answer,index)=><div className="choice-row" key={index}><input value={answer} onChange={(e)=>onChange({...block,matcher:{...matcher,accepted:matcher.accepted.map((a,i)=>i===index?e.target.value:a)}})}/><button type="button" className="text-button" disabled={matcher.accepted.length<=1} onClick={()=>onChange({...block,matcher:{...matcher,accepted:matcher.accepted.filter((_,i)=>i!==index)}})}>Remove</button></div>)}<button type="button" className="secondary" onClick={()=>onChange({...block,matcher:{...matcher,accepted:[...matcher.accepted,""]}})}>+ Accepted answer</button>{matcher.type==="FUZZY"&&<label>Similarity threshold ({Math.round(matcher.threshold*100)}%)<input type="range" min="0" max="1" step="0.01" value={matcher.threshold} onChange={(e)=>onChange({...block,matcher:{...matcher,threshold:n(e.target.value)}})}/></label>}<fieldset><legend>Normalization</legend><div className="check-grid"><label className="check"><input type="checkbox" checked={matcher.normalization.trim} onChange={(e)=>onChange({...block,matcher:{...matcher,normalization:{...matcher.normalization,trim:e.target.checked}}})}/>Trim spaces</label><label className="check"><input type="checkbox" checked={matcher.normalization.collapseWhitespace} onChange={(e)=>onChange({...block,matcher:{...matcher,normalization:{...matcher.normalization,collapseWhitespace:e.target.checked}}})}/>Collapse whitespace</label><label className="check"><input type="checkbox" checked={matcher.normalization.caseSensitive} onChange={(e)=>onChange({...block,matcher:{...matcher,normalization:{...matcher.normalization,caseSensitive:e.target.checked}}})}/>Case-sensitive</label><label className="check"><input type="checkbox" checked={Boolean(matcher.normalization.ignorePunctuation)} onChange={(e)=>onChange({...block,matcher:{...matcher,normalization:{...matcher.normalization,ignorePunctuation:e.target.checked}}})}/>Ignore punctuation</label></div></fieldset></>}</div>;
}

type NumberBlock=Extract<ActivityBlock,{type:"number_input"}>;
function NumberQuestionFields({block,onChange}:{block:NumberBlock;onChange:(block:ActivityBlock)=>void}){
  const acceptance=block.acceptance??{type:"MANUAL" as const};
  const setType=(type:NonNullable<NumberBlock["acceptance"]>["type"])=>{const next=type==="EXACT"?{type,value:0} as const:type==="RANGE"?{type,min:0,max:100} as const:type==="ABS_TOLERANCE"?{type,target:0,tolerance:1} as const:type==="PERCENT_TOLERANCE"?{type,target:100,percent:5} as const:{type:"MANUAL"} as const;onChange({...block,acceptance:next});};
  return <div className="stack"><div className="grid"><label>Prompt<textarea className="builder-prompt" value={block.prompt.default} onChange={(e)=>onChange({...block,prompt:withLabel(e.target.value)})}/></label><PromptMedia value={block.promptMediaAssetId} onChange={(promptMediaAssetId)=>onChange({...block,promptMediaAssetId})}/><label>Unit<input value={block.unit??""} onChange={(e)=>onChange({...block,unit:e.target.value||undefined})}/></label><label>Also record as metric<input value={block.metricKey??""} onChange={(e)=>onChange({...block,metricKey:e.target.value||undefined})} placeholder="optional metric key"/></label></div><label>Acceptance<select value={acceptance.type} onChange={(e)=>setType(e.target.value as typeof acceptance.type)}><option value="EXACT">Exact</option><option value="RANGE">Range</option><option value="ABS_TOLERANCE">Absolute tolerance</option><option value="PERCENT_TOLERANCE">Percent tolerance</option><option value="MANUAL">Manual review</option></select></label>{acceptance.type==="EXACT"&&<label>Correct value<input type="number" step="any" value={acceptance.value} onChange={(e)=>onChange({...block,acceptance:{...acceptance,value:n(e.target.value)}})}/></label>}{acceptance.type==="RANGE"&&<div className="grid"><label>Minimum<input type="number" step="any" value={acceptance.min??""} onChange={(e)=>onChange({...block,acceptance:{...acceptance,min:e.target.value===""?undefined:n(e.target.value)}})}/></label><label>Maximum<input type="number" step="any" value={acceptance.max??""} onChange={(e)=>onChange({...block,acceptance:{...acceptance,max:e.target.value===""?undefined:n(e.target.value)}})}/></label></div>}{acceptance.type==="ABS_TOLERANCE"&&<div className="grid"><label>Target<input type="number" step="any" value={acceptance.target} onChange={(e)=>onChange({...block,acceptance:{...acceptance,target:n(e.target.value)}})}/></label><label>± tolerance<input type="number" min="0" step="any" value={acceptance.tolerance} onChange={(e)=>onChange({...block,acceptance:{...acceptance,tolerance:Math.max(0,n(e.target.value))}})}/></label></div>}{acceptance.type==="PERCENT_TOLERANCE"&&<div className="grid"><label>Target<input type="number" step="any" value={acceptance.target} onChange={(e)=>onChange({...block,acceptance:{...acceptance,target:n(e.target.value)}})}/></label><label>± percent<input type="number" min="0" step="any" value={acceptance.percent} onChange={(e)=>onChange({...block,acceptance:{...acceptance,percent:Math.max(0,n(e.target.value))}})}/></label></div>}</div>;
}

type OrderingBlock=Extract<ActivityBlock,{type:"ordering"}>;
function OrderingFields({block,onChange}:{block:OrderingBlock;onChange:(block:ActivityBlock)=>void}){
  const add=()=>{const id=builderId("item");onChange({...block,items:[...block.items,{id,label:withLabel(`Item ${block.items.length+1}`)}],validation:{correctOrderIds:[...block.validation.correctOrderIds,id]}})};
  const remove=(id:string)=>onChange({...block,items:block.items.filter((item)=>item.id!==id),validation:{correctOrderIds:block.validation.correctOrderIds.filter((x)=>x!==id)}});
  const moveCorrect=(index:number,delta:-1|1)=>{const next=[...block.validation.correctOrderIds];const target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];onChange({...block,validation:{correctOrderIds:next}})};
  return <div className="stack"><div className="grid"><label>Prompt<textarea className="builder-prompt" value={block.prompt.default} onChange={(e)=>onChange({...block,prompt:withLabel(e.target.value)})}/></label><PromptMedia value={block.promptMediaAssetId} onChange={(promptMediaAssetId)=>onChange({...block,promptMediaAssetId})}/><label className="check"><input type="checkbox" checked={block.shuffleItems} onChange={(e)=>onChange({...block,shuffleItems:e.target.checked})}/>Shuffle for participants</label></div><strong>Items</strong>{block.items.map((item,index)=><div className="choice-row" key={item.id}><input value={inputLabel(item.label)} onChange={(e)=>onChange({...block,items:block.items.map((x,i)=>i===index?{...x,label:withLabel(e.target.value)}:x)})}/><button type="button" className="text-button" disabled={block.items.length<=2} onClick={()=>remove(item.id)}>Remove</button></div>)}<button type="button" className="secondary" onClick={add}>+ Item</button><strong>Correct order</strong>{block.validation.correctOrderIds.map((id,index)=>{const item=block.items.find((x)=>x.id===id);return <div className="choice-row" key={id}><span className="order-number">{index+1}</span><span>{inputLabel(item?.label)||id}</span><button type="button" className="icon-button" disabled={index===0} onClick={()=>moveCorrect(index,-1)}>↑</button><button type="button" className="icon-button" disabled={index===block.validation.correctOrderIds.length-1} onClick={()=>moveCorrect(index,1)}>↓</button></div>})}</div>;
}

type MatchingBlock=Extract<ActivityBlock,{type:"matching"}>;
function MatchingFields({block,onChange}:{block:MatchingBlock;onChange:(block:ActivityBlock)=>void}){
  const addPair=()=>{const leftId=builderId("left");const rightId=builderId("right");onChange({...block,leftItems:[...block.leftItems,{id:leftId,label:withLabel(`Left ${block.leftItems.length+1}`)}],rightItems:[...block.rightItems,{id:rightId,label:withLabel(`Right ${block.rightItems.length+1}`)}],validation:{pairs:[...block.validation.pairs,{leftId,rightId}]}})};
  const removeLeft=(id:string)=>onChange({...block,leftItems:block.leftItems.filter((x)=>x.id!==id),validation:{pairs:block.validation.pairs.filter((p)=>p.leftId!==id)}});
  return <div className="stack"><div className="grid"><label>Prompt<textarea className="builder-prompt" value={block.prompt.default} onChange={(e)=>onChange({...block,prompt:withLabel(e.target.value)})}/></label><PromptMedia value={block.promptMediaAssetId} onChange={(promptMediaAssetId)=>onChange({...block,promptMediaAssetId})}/><label className="check"><input type="checkbox" checked={block.shuffleRight} onChange={(e)=>onChange({...block,shuffleRight:e.target.checked})}/>Shuffle right side</label></div><strong>Pairs</strong>{block.leftItems.map((left,index)=>{const pair=block.validation.pairs.find((p)=>p.leftId===left.id);return <div className="match-row" key={left.id}><input value={left.label.default} onChange={(e)=>onChange({...block,leftItems:block.leftItems.map((x,i)=>i===index?{...x,label:withLabel(e.target.value)}:x)})}/><span>→</span><select value={pair?.rightId??""} onChange={(e)=>{const pairs=block.validation.pairs.filter((p)=>p.leftId!==left.id);onChange({...block,validation:{pairs:[...pairs,{leftId:left.id,rightId:e.target.value}]}})}}><option value="">Choose match</option>{block.rightItems.map((right)=><option key={right.id} value={right.id}>{right.label.default}</option>)}</select><button type="button" className="text-button" disabled={block.leftItems.length<=1} onClick={()=>removeLeft(left.id)}>Remove</button></div>})}<details><summary>Edit right-side labels</summary><div className="stack details-body">{block.rightItems.map((right,index)=><div className="choice-row" key={right.id}><input value={right.label.default} onChange={(e)=>onChange({...block,rightItems:block.rightItems.map((x,i)=>i===index?{...x,label:withLabel(e.target.value)}:x)})}/><button type="button" className="text-button" disabled={block.rightItems.length<=1} onClick={()=>onChange({...block,rightItems:block.rightItems.filter((_,i)=>i!==index),validation:{pairs:block.validation.pairs.filter((p)=>p.rightId!==right.id)}})}>Remove</button></div>)}</div></details><button type="button" className="secondary" onClick={addPair}>+ Pair</button></div>;
}

type RubricBlock=Extract<ActivityBlock,{type:"judge_rubric"}>;
function RubricFields({block,onChange}:{block:RubricBlock;onChange:(block:ActivityBlock)=>void}){
  return <div className="stack"><div className="grid"><label>Rubric key<input value={block.rubricKey} onChange={(e)=>onChange({...block,rubricKey:e.target.value})}/></label><label>Multiple judges<select value={block.aggregateJudges} onChange={(e)=>onChange({...block,aggregateJudges:e.target.value as typeof block.aggregateJudges})}><option value="AVERAGE">Average</option><option value="MEDIAN">Median</option><option value="SUM">Sum</option><option value="DROP_HIGH_LOW_AVERAGE">Drop high/low then average</option></select></label></div><strong>Criteria</strong>{block.criteria.map((criterion,index)=><div className="subcard grid" key={criterion.id}><label>Criterion<input value={criterion.label.default} onChange={(e)=>onChange({...block,criteria:block.criteria.map((c,i)=>i===index?{...c,label:withLabel(e.target.value)}:c)})}/></label><label>Weight<input type="number" min="0.0001" step="any" value={criterion.weight} onChange={(e)=>onChange({...block,criteria:block.criteria.map((c,i)=>i===index?{...c,weight:Math.max(0.0001,n(e.target.value,1))}:c)})}/></label><label>Scale min<input type="number" step="any" value={criterion.scale.min} onChange={(e)=>onChange({...block,criteria:block.criteria.map((c,i)=>i===index?{...c,scale:{...c.scale,min:n(e.target.value)}}:c)})}/></label><label>Scale max<input type="number" step="any" value={criterion.scale.max} onChange={(e)=>onChange({...block,criteria:block.criteria.map((c,i)=>i===index?{...c,scale:{...c.scale,max:n(e.target.value,10)}}:c)})}/></label><label>Step<input type="number" min="0.0001" step="any" value={criterion.scale.step??""} onChange={(e)=>onChange({...block,criteria:block.criteria.map((c,i)=>i===index?{...c,scale:{...c.scale,step:e.target.value?Math.max(0.0001,n(e.target.value)):undefined}}:c)})}/></label><div className="form-actions"><button type="button" className="text-button danger-text" disabled={block.criteria.length<=1} onClick={()=>onChange({...block,criteria:block.criteria.filter((_,i)=>i!==index)})}>Remove criterion</button></div></div>)}<button type="button" className="secondary" onClick={()=>onChange({...block,criteria:[...block.criteria,{id:builderId("criterion"),label:withLabel(`Criterion ${block.criteria.length+1}`),weight:1,scale:{min:1,max:10,step:1}}]})}>+ Criterion</button></div>;
}

type PoolBlock=Extract<ActivityBlock,{type:"question_pool"}>;
function QuestionPoolFields({block,onChange}:{block:PoolBlock;onChange:(block:ActivityBlock)=>void}){
  const [newType,setNewType]=useState<QuestionBlock["type"]>("single_select");
  const move=(index:number,direction:-1|1)=>{const next=[...block.questions];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];onChange({...block,questions:next});};
  return <div className="stack"><div className="grid"><label>Pool intro<input value={block.intro?.default??""} onChange={(e)=>onChange({...block,intro:e.target.value?withLabel(e.target.value):undefined})}/></label><label>Selection mode<select value={block.mode} onChange={(e)=>onChange({...block,mode:e.target.value as typeof block.mode,drawCount:e.target.value==="RANDOM_N"?(block.drawCount??1):undefined})}><option value="ALL">Use all questions</option><option value="RANDOM_N">Random N per run</option></select></label>{block.mode==="RANDOM_N"&&<label>Questions per run<input type="number" min="1" max={block.questions.length} value={block.drawCount??1} onChange={(e)=>onChange({...block,drawCount:Math.max(1,Number(e.target.value)||1)})}/></label>}<label className="check"><input type="checkbox" checked={block.shuffleSelected} onChange={(e)=>onChange({...block,shuffleSelected:e.target.checked})}/>Shuffle selected order</label></div><div className="notice"><strong>Question bank</strong><span>{block.questions.length} authored questions. Random selection is generated and pinned when a run starts.</span></div><div className="builder-block-list nested-bank">{block.questions.map((question,index)=><BlockEditor key={question.id} block={question} index={index} total={block.questions.length} allowedTypes={QUESTION_TYPES} onMove={(direction)=>move(index,direction)} onRemove={()=>{if(block.questions.length<=1)return;onChange({...block,questions:block.questions.filter((_,i)=>i!==index),drawCount:block.drawCount?Math.min(block.drawCount,block.questions.length-1):block.drawCount})}} onChange={(next)=>{if(!isQuestion(next))return;onChange({...block,questions:block.questions.map((q,i)=>i===index?next:q)})}}/>)}</div><div className="builder-addbar"><select value={newType} onChange={(e)=>setNewType(e.target.value as QuestionBlock["type"])}>{BLOCK_CATALOG.filter((item)=>QUESTION_TYPES.includes(item.type as QuestionBlock["type"])).map((item)=><option key={item.type} value={item.type}>{item.label}</option>)}</select><button type="button" onClick={()=>{const next=createBlock(newType);if(isQuestion(next))onChange({...block,questions:[...block.questions,next]})}}>+ Add question to bank</button></div></div>;
}

function QuestionMeta({block,onChange}:{block:QuestionBlock;onChange:(block:ActivityBlock)=>void}){
  const legacy=block.type==="single_select"?block.scoring:undefined;
  const grading=block.grading;
  return <details className="subcard" open><summary>Question behavior: hint, timer, attempts & points</summary><div className="grid details-body"><label className="full-span">Hint<input value={block.hint?.default??""} onChange={(e)=>onChange({...block,hint:e.target.value?withLabel(e.target.value):undefined})}/></label><label>Per-question time limit (seconds)<input type="number" min="1" value={block.timeLimitMs?block.timeLimitMs/1000:""} onChange={(e)=>onChange({...block,timeLimitMs:e.target.value?Math.max(1,n(e.target.value))*1000:undefined})}/></label><label>Attempts for this question<input type="number" min="1" value={block.maxAttempts??""} onChange={(e)=>onChange({...block,maxAttempts:e.target.value?Math.max(1,n(e.target.value)):undefined})}/></label><label className="check"><input type="checkbox" checked={Boolean(grading)} onChange={(e)=>onChange({...block,grading:e.target.checked?{correctPoints:legacy?.correct??1,incorrectPoints:legacy?.incorrect??0,partialCredit:"PROPORTIONAL"}:undefined})}/>Assign question points</label>{grading&&<><label>Correct points<input type="number" step="any" value={grading.correctPoints} onChange={(e)=>onChange({...block,grading:{...grading,correctPoints:n(e.target.value)}})}/></label><label>Incorrect points<input type="number" step="any" value={grading.incorrectPoints} onChange={(e)=>onChange({...block,grading:{...grading,incorrectPoints:n(e.target.value)}})}/></label><label>Partial credit<select value={grading.partialCredit} onChange={(e)=>onChange({...block,grading:{...grading,partialCredit:e.target.value as typeof grading.partialCredit}})}><option value="PROPORTIONAL">Proportional</option><option value="NONE">No partial credit</option></select></label></>}</div></details>;
}
