"use client";

import type { ConditionExpr, RuleDefinition, ValueExpr } from "@/schemas/rules";
import type { ScoreExpr } from "@/schemas/scoring";
import { createCondition, createScoreExpr, createValueExpr } from "./model";

type MetricOption = { key: string; label: string };
type ActivityOption = { id: string; title: string };
const scoreTypes: ScoreExpr["type"][] = ["constant", "metric", "add", "subtract", "multiply", "divide", "min", "max", "clamp", "round", "if"];
const valueTypes: ValueExpr["type"][] = ["literal", "metric", "score", "run", "event", "variable"];
const compareOps = ["EQ", "NE", "GT", "GTE", "LT", "LTE", "IN", "NOT_IN"] as const;

function num(value: string, fallback = 0) { const n = Number(value); return Number.isFinite(n) ? n : fallback; }

export function ValueExprEditor({ value, onChange, metrics }: { value: ValueExpr; onChange: (value: ValueExpr) => void; metrics: MetricOption[] }) {
  return <div className="expr-row">
    <select value={value.type} onChange={(e) => onChange(createValueExpr(e.target.value as ValueExpr["type"], metrics[0]?.key))}>{valueTypes.map((type)=><option key={type} value={type}>{type}</option>)}</select>
    {value.type === "literal" && <input value={String(value.value ?? "")} onChange={(e)=>{ const raw=e.target.value; const parsed=raw === "true" ? true : raw === "false" ? false : raw.trim() !== "" && Number.isFinite(Number(raw)) ? Number(raw) : raw; onChange({ ...value, value: parsed }); }} placeholder="literal value"/>}
    {value.type === "metric" && <select value={value.key} onChange={(e)=>onChange({...value,key:e.target.value})}>{metrics.length ? metrics.map((m)=><option key={m.key} value={m.key}>{m.label} ({m.key})</option>) : <option value={value.key}>No metrics yet</option>}</select>}
    {value.type === "score" && <><select value={value.scope} onChange={(e)=>onChange({...value,scope:e.target.value as "ACTIVITY"|"EVENT"})}><option value="ACTIVITY">Activity score</option><option value="EVENT">Event score</option></select><input value={value.key ?? ""} onChange={(e)=>onChange({...value,key:e.target.value || undefined})} placeholder="optional score key"/></>}
    {value.type === "run" && <select value={value.field} onChange={(e)=>onChange({...value,field:e.target.value as typeof value.field})}><option value="attemptNo">Attempt number</option><option value="elapsedMs">Elapsed ms</option><option value="status">Run status</option></select>}
    {value.type === "event" && <select value={value.field} onChange={(e)=>onChange({...value,field:e.target.value as typeof value.field})}><option value="state">Event state</option><option value="now">Current time</option></select>}
    {value.type === "variable" && <><input value={value.scope} onChange={(e)=>onChange({...value,scope:e.target.value})} placeholder="scope"/><input value={value.key} onChange={(e)=>onChange({...value,key:e.target.value})} placeholder="key"/></>}
  </div>;
}

export function ConditionEditor({ value, onChange, metrics, depth = 0 }: { value: ConditionExpr; onChange: (value: ConditionExpr) => void; metrics: MetricOption[]; depth?: number }) {
  const types: ConditionExpr["type"][] = ["compare", "exists", "all", "any", "not"];
  return <div className="expr-node">
    <div className="expr-row"><select value={value.type} onChange={(e)=>onChange(createCondition(e.target.value as ConditionExpr["type"]))}>{types.map((t)=><option key={t} value={t}>{t}</option>)}</select></div>
    {value.type === "compare" && <div className="expr-grid"><ValueExprEditor value={value.left} metrics={metrics} onChange={(left)=>onChange({...value,left})}/><select value={value.op} onChange={(e)=>onChange({...value,op:e.target.value as typeof value.op})}>{compareOps.map((op)=><option key={op}>{op}</option>)}</select><ValueExprEditor value={value.right} metrics={metrics} onChange={(right)=>onChange({...value,right})}/></div>}
    {value.type === "exists" && <ValueExprEditor value={value.value} metrics={metrics} onChange={(next)=>onChange({...value,value:next})}/>} 
    {(value.type === "all" || value.type === "any") && <div className="stack">{value.conditions.map((condition,index)=><div className="expr-child" key={index}><ConditionEditor value={condition} metrics={metrics} depth={depth+1} onChange={(next)=>onChange({...value,conditions:value.conditions.map((c,i)=>i===index?next:c)})}/><button type="button" className="text-button danger-text" onClick={()=>onChange({...value,conditions:value.conditions.filter((_,i)=>i!==index)})}>Remove condition</button></div>)}<button type="button" className="secondary" onClick={()=>onChange({...value,conditions:[...value.conditions,createCondition()]})}>+ Condition</button></div>}
    {value.type === "not" && <ConditionEditor value={value.condition} metrics={metrics} depth={depth+1} onChange={(condition)=>onChange({...value,condition})}/>} 
  </div>;
}

export function ScoreExprEditor({ value, onChange, metrics, depth = 0 }: { value: ScoreExpr; onChange: (value: ScoreExpr) => void; metrics: MetricOption[]; depth?: number }) {
  const metricFallback=metrics[0]?.key;
  return <div className="expr-node">
    <div className="expr-row"><select value={value.type} onChange={(e)=>onChange(createScoreExpr(e.target.value as ScoreExpr["type"],metricFallback))}>{scoreTypes.map((t)=><option key={t} value={t}>{t}</option>)}</select></div>
    {value.type === "constant" && <label>Value<input type="number" step="any" value={value.value} onChange={(e)=>onChange({...value,value:num(e.target.value)})}/></label>}
    {value.type === "metric" && <label>Metric<select value={value.key} onChange={(e)=>onChange({...value,key:e.target.value})}>{metrics.length?metrics.map((m)=><option key={m.key} value={m.key}>{m.label} ({m.key})</option>):<option value={value.key}>No metrics yet</option>}</select></label>}
    {(value.type === "add" || value.type === "multiply" || value.type === "min" || value.type === "max") && <div className="stack">{value.values.map((expr,index)=><div className="expr-child" key={index}><ScoreExprEditor value={expr} metrics={metrics} depth={depth+1} onChange={(next)=>onChange({...value,values:value.values.map((x,i)=>i===index?next:x)})}/>{value.values.length>1&&<button type="button" className="text-button danger-text" onClick={()=>onChange({...value,values:value.values.filter((_,i)=>i!==index)})}>Remove operand</button>}</div>)}<button type="button" className="secondary" onClick={()=>onChange({...value,values:[...value.values,{type:"constant",value:value.type==="multiply"?1:0}]})}>+ Operand</button></div>}
    {value.type === "subtract" && <div className="expr-grid"><div><small>Left</small><ScoreExprEditor value={value.left} metrics={metrics} depth={depth+1} onChange={(left)=>onChange({...value,left})}/></div><div><small>Right</small><ScoreExprEditor value={value.right} metrics={metrics} depth={depth+1} onChange={(right)=>onChange({...value,right})}/></div></div>}
    {value.type === "divide" && <div className="expr-grid"><div><small>Numerator</small><ScoreExprEditor value={value.numerator} metrics={metrics} depth={depth+1} onChange={(numerator)=>onChange({...value,numerator})}/></div><div><small>Denominator</small><ScoreExprEditor value={value.denominator} metrics={metrics} depth={depth+1} onChange={(denominator)=>onChange({...value,denominator})}/></div><label>When denominator is zero<input type="number" step="any" value={value.onZero} onChange={(e)=>onChange({...value,onZero:num(e.target.value)})}/></label></div>}
    {value.type === "clamp" && <div className="stack"><ScoreExprEditor value={value.value} metrics={metrics} depth={depth+1} onChange={(next)=>onChange({...value,value:next})}/><div className="grid"><label>Minimum<input type="number" step="any" value={value.min ?? ""} onChange={(e)=>onChange({...value,min:e.target.value===""?undefined:num(e.target.value)})}/></label><label>Maximum<input type="number" step="any" value={value.max ?? ""} onChange={(e)=>onChange({...value,max:e.target.value===""?undefined:num(e.target.value)})}/></label></div></div>}
    {value.type === "round" && <div className="stack"><ScoreExprEditor value={value.value} metrics={metrics} depth={depth+1} onChange={(next)=>onChange({...value,value:next})}/><label>Decimals<input type="number" min="0" max="8" value={value.decimals} onChange={(e)=>onChange({...value,decimals:num(e.target.value)})}/></label></div>}
    {value.type === "if" && <div className="stack"><div><small>If</small><ConditionEditor value={value.condition} metrics={metrics} onChange={(condition)=>onChange({...value,condition})}/></div><div><small>Then</small><ScoreExprEditor value={value.then} metrics={metrics} depth={depth+1} onChange={(then)=>onChange({...value,then})}/></div><div><small>Else</small><ScoreExprEditor value={value.else} metrics={metrics} depth={depth+1} onChange={(otherwise)=>onChange({...value,else:otherwise})}/></div></div>}
  </div>;
}

function createAction(type: RuleDefinition["actions"][number]["type"], metricKey?: string): RuleDefinition["actions"][number] {
  if(type==="ADD_SCORE") return {type,amount:createValueExpr("literal",metricKey),dimensionKey:"event_points",reason:"Configured rule"};
  if(type==="UNLOCK_ACTIVITY") return {type,activityId:""};
  return {type:"MARK_RUN_FAILED"};
}

export function RuleEditor({ rule, onChange, metrics, activities }: { rule: RuleDefinition; onChange:(rule:RuleDefinition)=>void; metrics:MetricOption[]; activities:ActivityOption[] }) {
  return <div className="subcard stack">
    <div className="grid"><label>Rule name<input value={rule.name ?? ""} onChange={(e)=>onChange({...rule,name:e.target.value})}/></label><label className="check"><input type="checkbox" checked={rule.enabled} onChange={(e)=>onChange({...rule,enabled:e.target.checked})}/>Enabled</label></div>
    <div className="grid"><label>When<select value={rule.trigger.type} onChange={(e)=>{const type=e.target.value as RuleDefinition["trigger"]["type"]; onChange({...rule,trigger:type==="TIMER_EXPIRED"?{type,timerKey:"main"}:type==="MANUAL"?{type,key:"manual"}:{type}})}}><option value="ACTIVITY_RUN_COMPLETED">Activity completed</option><option value="SUBMISSION_ACCEPTED">Submission accepted</option><option value="TIMER_EXPIRED">Timer expired</option><option value="MANUAL">Manual trigger</option></select></label>{rule.trigger.type==="TIMER_EXPIRED"&&<label>Timer key<input value={rule.trigger.timerKey} onChange={(e)=>onChange({...rule,trigger:{type:"TIMER_EXPIRED",timerKey:e.target.value}})}/></label>}{rule.trigger.type==="MANUAL"&&<label>Manual key<input value={rule.trigger.key} onChange={(e)=>onChange({...rule,trigger:{type:"MANUAL",key:e.target.value}})}/></label>}</div>
    <div><div className="row"><strong>IF condition</strong>{rule.condition?<button type="button" className="text-button danger-text" onClick={()=>{const {condition:_c,...rest}=rule;onChange(rest as RuleDefinition)}}>Remove condition</button>:<button type="button" className="secondary" onClick={()=>onChange({...rule,condition:createCondition()})}>+ Add condition</button>}</div>{rule.condition&&<ConditionEditor value={rule.condition} metrics={metrics} onChange={(condition)=>onChange({...rule,condition})}/>}</div>
    <div className="stack"><strong>THEN actions</strong>{rule.actions.map((action,index)=><div className="subcard" key={index}><div className="row"><select value={action.type} onChange={(e)=>onChange({...rule,actions:rule.actions.map((a,i)=>i===index?createAction(e.target.value as typeof action.type,metrics[0]?.key):a)})}><option value="ADD_SCORE">Add score</option><option value="MARK_RUN_FAILED">Mark run failed</option><option value="UNLOCK_ACTIVITY">Unlock activity</option></select>{rule.actions.length>1&&<button type="button" className="text-button danger-text" onClick={()=>onChange({...rule,actions:rule.actions.filter((_,i)=>i!==index)})}>Remove</button>}</div>{action.type==="ADD_SCORE"&&<div className="stack"><label>Dimension<input value={action.dimensionKey} onChange={(e)=>onChange({...rule,actions:rule.actions.map((a,i)=>i===index&&a.type==="ADD_SCORE"?{...a,dimensionKey:e.target.value}:a)})}/></label><label>Reason<input value={action.reason} onChange={(e)=>onChange({...rule,actions:rule.actions.map((a,i)=>i===index&&a.type==="ADD_SCORE"?{...a,reason:e.target.value}:a)})}/></label><ValueExprEditor value={action.amount} metrics={metrics} onChange={(amount)=>onChange({...rule,actions:rule.actions.map((a,i)=>i===index&&a.type==="ADD_SCORE"?{...a,amount}:a)})}/></div>}{action.type==="UNLOCK_ACTIVITY"&&<label>Activity<select value={action.activityId} onChange={(e)=>onChange({...rule,actions:rule.actions.map((a,i)=>i===index&&a.type==="UNLOCK_ACTIVITY"?{...a,activityId:e.target.value}:a)})}><option value="">Select activity</option>{activities.map((a)=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>}</div>)}<button type="button" className="secondary" onClick={()=>onChange({...rule,actions:[...rule.actions,createAction("ADD_SCORE",metrics[0]?.key)]})}>+ Action</button></div>
    <div className="grid"><label>Run at most<select value={rule.executionPolicy?.oncePer ?? "ACTIVITY_RUN"} onChange={(e)=>onChange({...rule,executionPolicy:{...rule.executionPolicy,oncePer:e.target.value as NonNullable<RuleDefinition["executionPolicy"]>["oncePer"]}})}><option value="EVENT">Once per event</option><option value="TEAM">Once per team</option><option value="ENTRY">Once per participant entry</option><option value="ACTIVITY_RUN">Once per run</option><option value="TRIGGER_OCCURRENCE">Every trigger occurrence</option></select></label><label>Max executions<input type="number" min="1" max="1000" value={rule.executionPolicy?.maxExecutions ?? ""} onChange={(e)=>onChange({...rule,executionPolicy:{...rule.executionPolicy,maxExecutions:e.target.value?num(e.target.value):undefined}})}/></label></div>
  </div>;
}
