import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getCurrentUser } from "@/server/auth/session";
import { requireEventCapability } from "@/server/permissions/capabilities";
import { getPrisma } from "@/lib/prisma";
import { MatchResultSchema, RoundRobinConfigSchema } from "@/schemas/results";
import { CompetitionService } from "@/server/services/competition-service";
import { finalizeCompetition, recordMatchResult } from "./actions";

const resolvedStates=new Set(["FINAL","BYE","WALKOVER","VOID","CANCELLED"]);
export default async function CompetitionPage({params}:{params:Promise<{eventId:string;competitionId:string}>}){
  const user=await getCurrentUser();if(!user)redirect("/login");const {eventId,competitionId}=await params;await requireEventCapability(user.id,eventId,"event.read");
  const competition=await getPrisma().competition.findUnique({where:{id:competitionId},include:{activity:true,event:true,matches:{include:{sides:{include:{participationEntry:{include:{team:true}}}}},orderBy:[{roundKey:"asc"},{sequence:"asc"}]}}});if(!competition||competition.eventId!==eventId)notFound();
  const grouped=new Map<string,typeof competition.matches>();for(const match of competition.matches){const list=grouped.get(match.roundKey)??[];list.push(match);grouped.set(match.roundKey,list);}
  const roundRobin=competition.formatKey==="round_robin"?await new CompetitionService().roundRobinStandings(competition.id):null;const rrConfig=competition.formatKey==="round_robin"?RoundRobinConfigSchema.parse(competition.configJson??{}):null;
  const allResolved=competition.matches.length>0&&competition.matches.every((match)=>resolvedStates.has(match.state));
  return <main><div className="page-heading"><div><Link href={`/admin/events/${eventId}/competitions`}>← Competitions</Link><div className="row"><h1>{competition.name}</h1><span className="badge">{competition.state}</span></div><p className="muted"><code>{competition.formatKey}</code>{competition.activity?` · ${competition.activity.title}`:""}</p></div>{allResolved&&competition.state!=="FINALIZED"&&<form action={finalizeCompetition}><input type="hidden" name="eventId" value={eventId}/><input type="hidden" name="competitionId" value={competition.id}/><button>Finalize competition</button></form>}</div>
    {roundRobin&&<section className="card"><div className="section-heading"><div><h2>Round-robin standings</h2><p className="muted">Win {rrConfig!.winPoints} · draw {rrConfig!.drawPoints} · loss {rrConfig!.lossPoints}. Default generic tie order: points → wins → score difference → score for.</p></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Entry</th><th>P</th><th>W</th><th>D</th><th>L</th><th>For</th><th>Against</th><th>Diff</th><th>Pts</th></tr></thead><tbody>{roundRobin.map((row)=>{const entry=competition.matches.flatMap((m)=>m.sides).find((s)=>s.participationEntryId===row.entryId)?.participationEntry;return <tr key={row.entryId}><td>{row.rank}</td><td>{entry?.team?.name||entry?.label||row.entryId.slice(0,8)}</td><td>{row.played}</td><td>{row.wins}</td><td>{row.draws}</td><td>{row.losses}</td><td>{row.scoreFor}</td><td>{row.scoreAgainst}</td><td>{row.scoreDiff}</td><td><strong>{row.points}</strong></td></tr>})}</tbody></table></div></section>}
    {[...grouped.entries()].map(([round,matches])=><section className="card" key={round}><h2>Round {round}</h2><div className="match-grid">{matches.map((match)=>{let result:null|ReturnType<typeof MatchResultSchema.parse>=null;try{if(match.resultJson)result=MatchResultSchema.parse(match.resultJson)}catch{}return <article className="subcard match-card" key={match.id}><div className="section-heading"><strong>Match {match.sequence}</strong><span className="badge">{match.state}</span></div><div className="match-sides">{match.sides.map((side)=><div className={`match-side ${side.isWinner?"winner":""}`} key={side.id}><span>{side.participationEntry.team?.name||side.participationEntry.label||side.participationEntryId.slice(0,8)}</span>{side.isWinner&&<strong>Winner</strong>}{typeof (side.resultJson as {score?:unknown}|null)?.score==="number"&&<b>{String((side.resultJson as {score:number}).score)}</b>}</div>)}</div>{match.state==="BYE"?<p className="muted">Automatic bye → {match.sides[0]?.participationEntry.team?.name||"entrant"} advances.</p>:<form action={recordMatchResult} className="stack"><input type="hidden" name="eventId" value={eventId}/><input type="hidden" name="matchId" value={match.id}/><input type="hidden" name="idempotencyKey" value={randomUUID()}/>{match.sides.map((side)=><label key={side.id}>{side.participationEntry.team?.name||side.participationEntry.label||"Entry"} score<input name={`score:${side.participationEntryId}`} type="number" step="any" defaultValue={typeof (side.resultJson as {score?:unknown}|null)?.score==="number"?String((side.resultJson as {score:number}).score):""}/></label>)}<label>Winner<select name="winnerEntryId" defaultValue={result?.winnerEntryId??""}><option value="">Draw / no winner</option>{match.sides.map((side)=><option key={side.id} value={side.participationEntryId}>{side.participationEntry.team?.name||side.participationEntry.label||"Entry"}</option>)}</select></label><label>Note<input name="note" defaultValue={result?.note??""}/></label><button className="secondary">{match.state==="FINAL"?"Correct result":"Finalize result"}</button></form>}</article>})}</div></section>)}
  </main>;
}
